server.port=8080

url-shortener.base-url=http://localhost:8082
url-shortener.cleanup-interval-ms=60000

spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=urluser
spring.datasource.password=urlpassword
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
