server.port=8080

url-shortener.base-url=http://localhost:8082
url-shortener.cleanup-interval-ms=60000

spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.keyspace-name=urlshortener
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=create_if_not_exists
