server.port=8080

url-shortener.base-url=http://localhost:8082
url-shortener.ttl-seconds=60
url-shortener.code-length=7

spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=urluser
spring.datasource.password=urlpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
