server.port=8080

url-shortener.base-url=http://localhost:8082
url-shortener.ttl-seconds=60
url-shortener.code-length=7

spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.keyspace-name=urlshortener
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=create_if_not_exists

# Kafka (producent zdarzen blocklist)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Lista zakazanych slow w URL + topic Kafki
blocklist.topic=url-blocklist-events
blocklist.words=casino,porn,malware,phishing,xxx
